name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
          # 3. SBT installieren
    - name: Setup SBT
      uses: coursier/setup-action@v1
      with:
        apps: sbt

      # 4. Projekt bauen mit sbt assembly
    - name: Build with sbt assembly
      run: sbt assembly
    - name: Run tests
      run: sbt test
